name: Push Container to Heroku

on: 
  push:
    branches:
      - master

jobs:
  loadtest:
    name: k6 local test run 
    runs-on: ubuntu-latest
    container: docker://loadimpact/k6:latest
    needs: [build]
  
    steps:
    - name: Echo port
      run: echo "${{needs.build.outputs.output_port}}"
      
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Run k6 local test
      uses: k6io/action@v0.1
      with:
        filename: script.js
      env:
        HOST: ${{ secrets.HEROKU_APP_NAME }}
        PORT: ${{ needs.build.outputs.output_port }}